#pragma once

//Define player state animation ID

#define PLAYER_IDLE_RIGHT_ANIMATION 300
#define PLAYER_IDLE_LEFT_ANIMATION 301
#define PLAYER_RUN_RIGHT_ANIMATION 302
#define PLAYER_RUN_LEFT_ANIMATION 303
#define PLAYER_GUN_UP_RIGHT_ANIMATION 304
#define PLAYER_GUN_UP_LEFT_ANIMATION 305
#define PLAYER_LAY_DOWN_RIGHT_ANIMATION 306
#define PLAYER_LAY_DOWN_LEFT_ANIMATION 307
#define PLAYER_GUN_TOP_RIGHT_ANIMATION 308
#define PLAYER_GUN_TOP_LEFT_ANIMATION 309
#define PLAYER_GUN_DOWN_RIGHT_ANIMATION 310
#define PLAYER_GUN_DOWN_LEFT_ANIMATION 311
#define PLAYER_JUMP_UP_RIGHT_ANIMATION 312
#define PLAYER_JUMP_UP_LEFT_ANIMATION 313
#define PLAYER_DIE_RIGHT_ANIMATION 314
#define PLAYER_DIE_LEFT_ANIMATION 315
#define PLAYER_LAY_DIE_RIGHT_ANIMATION 316
#define PLAYER_LAY_DIE_LEFT_ANIMATION 317
#define PLAYER_SHOOT_RUN_RIGHT_ANIMATION 318
#define PLAYER_SHOOT_RUN_LEFT_ANIMATION 319
#define PLAYER_STAND_RIGHT_SHOOT_ANIMATION 320
#define PLAYER_STAND_LEFT_SHOOT_ANIMATION 321
#define PLAYER_GUN_UP_RIGHT_SHOOT_ANIMATION 322
#define PLAYER_GUN_UP_LEFT_SHOOT_ANIMATION 323
#define PLAYER_LAY_DOWN_RIGHT_SHOOT_ANIMATION 324
#define PLAYER_LAY_DOWN_LEFT_SHOOT_ANIMATION 325
#define PLAYER_LAY_DOWN_IN_WATER_ANIMATION 326
#define PLAYER_STAND_RIGHT_IN_WATER_ANIMATION 327
#define PLAYER_STAND_LEFT_IN_WATER_ANIMATION 328
#define PLAYER_RUN_RIGHT_IN_WATER_ANIMTION 329
#define PLAYER_RUN_LEFT_IN_WATER_ANIMTION 330
#define PLAYER_SHOOT_RIGHT_IN_WATER_ANIMATION 331
#define PLAYER_SHOOT_LEFT_IN_WATER_ANIMATION 332
#define PLAYER_TOP_RIGHT_IN_WATER_ANIMATION 333
#define PLAYER_TOP_LEFT_IN_WATER_ANIMATION 334
#define PLAYER_GUN_UP_RIGHT_IN_WATER_ANIMATION 335
#define PLAYER_GUN_UP_LEFT_IN_WATER_ANIMATION 336
#define PLAYER_GUN_UP_SHOOT_RIGHT_IN_WATER_ANIMATION 337
#define PLAYER_GUN_UP_SHOOT_LEFT_IN_WATER_ANIMATION 338

//runman define

#define TEXTURE_PATH_RUNMAN_RIGHT L"image\\Enemy\\run_man_right.png"

#define RUNMAN_SPRITE_WIDTH 24
#define RUNMAN_SPRITE_HEIGHT 36

#define RUNMAN_RUN_LEFT_ANIMATION 100
#define RUNMAN_RUN_RIGHT_ANIMATION 101

//turret define

#define TEXTURE_PATH_TURRET_CLOSE L"image\\Enemy\\Turret\\Turret_Close.png"
#define TEXTURE_PATH_TURRET_OPENING L"image\\Enemy\\Turret\\Turret_Opening.png"
#define TEXTURE_PATH_TURRET_0 L"image\\Enemy\\Turret\\Turret_0.png"
#define TEXTURE_PATH_TURRET_30 L"image\\Enemy\\Turret\\Turret_30.png"
#define TEXTURE_PATH_TURRET_60 L"image\\Enemy\\Turret\\Turret_60.png"
#define TEXTURE_PATH_TURRET_90 L"image\\Enemy\\Turret\\Turret_90.png"
#define TEXTURE_PATH_TURRET_120 L"image\\Enemy\\Turret\\Turret_120.png"
#define TEXTURE_PATH_TURRET_150 L"image\\Enemy\\Turret\\Turret_150.png"

#define TURRET_CLOSE_ANIMATION 3000
#define TURRET_OPENING_ANIMATION 3001
#define TURRET_0_ANIMATION 3002
#define TURRET_30_ANIMATION 3003
#define TURRET_n30_ANIMATION 3004
#define TURRET_60_ANIMATION 3005
#define TURRET_n60_ANIMATION 3006
#define TURRET_90_ANIMATION 3007
#define TURRET_n90_ANIMATION 3008
#define TURRET_120_ANIMATION 3009
#define TURRET_n120_ANIMATION 3010
#define TURRET_150_ANIMATION 3011
#define TURRET_n150_ANIMATION 3012
#define TURRET_180_ANIMATION 3013

#define TURRET_SPRITE_HEIGHT 32
#define TURRET_SPRITE_WIDTH 32


//bullet define
#define TEXTURE_PATH_NORMAL_BULLET L"image\\Bullet\\bullet_b.png"

#define NORMAL_BULLET 400

//asset define
#define TEXTURE_PATH_LIFE L"image\\Asset\\life.png"

#define LIFE_ASSET_WIDTH 28
#define PLAYER_LIFE 450


//effect define
#define TEXTURE_PATH_DIE_EFFECT L"image\\Effect\\die_effect.png"

#define DIE_EFFECT_SPRITE_WIDTH 32
#define DIE_EFFECT_SPRITE_HEIGHT 32

#define DIE_EFFECT_ANIMATION 500

// List of path scene
#define PATH_SCENE_0 L"SceneInfo\\Scene0.txt"

enum shootingDirection
{
	SHOOT_LEFT,
	SHOOT_RIGHT,
	SHOOT_TOP,
	SHOOT_TOPLEFT,
	SHOOT_TOPRIGHT,
	SHOOT_DOWNLEFT,
	SHOOT_DOWNRIGHT
};